language: python
python:
  - "2.7"
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/indigo_test
before_install:
  - "rvm install ruby-2.3.3"
  - "rvm use ruby-2.3.3"
install: 
  - "pip install .[test]"
  - "bundle install"
  - "npm install -g jshint"
script: coverage run manage.py test && jshint indigo_app/static/javascript/indigo/
after_success:
  - coveralls
